<a href="https://colab.research.google.com/github/priyagarg1304/COURSERA-TEST/blob/master/chatbot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
pip install chatterbot

ERROR: chatterbot-corpus 1.2.0 has requirement PyYAML<4.0,>=3.12, but you'll have pyyaml 5.1.2 which is incompatible.
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [14]:
pip install chatterbot-corpus

ERROR: chatterbot 1.0.5 has requirement pyyaml<5.2,>=5.1, but you'll have pyyaml 3.13 which is incompatible.
  Found existing installation: PyYAML 5.1.2
    Uninstalling PyYAML-5.1.2:
      Successfully uninstalled PyYAML-5.1.2


In [10]:
from chatterbot import ChatBot
chatbot = ChatBot("Ron Obvious")

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [72]:
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot

#creating a new chatbot
chatbot = ChatBot('My')
trainer = ListTrainer(chatbot)
trainer.train([ 'Where do you live','I am a computer', 'What is your state?','Delhi', 'what is your district','Delhi'])
 


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
List Trainer: [####################] 100%


In [45]:
from google.colab import files
uploaded = files.upload()

Saving crop_production.csv to crop_production.csv


In [53]:

import numpy as np
data = pandas.read_csv('crop_production.csv')
data = data.drop('Crop_Year',1)
from sklearn.preprocessing import LabelEncoder 
crops=np.unique(data['Crop'])
states=np.unique(data['State_Name'])
districts=np.unique(data['District_Name'])

le = LabelEncoder() 
  
data['Crop']= le.fit_transform(data['Crop']) 
data['State_Name']= le.fit_transform(data['State_Name'])
data['District_Name']= le.fit_transform(data['District_Name'])
data['Season']= le.fit_transform(data['Season']) 
print(data)

        State_Name  District_Name  Season  Crop      Area   Production
0                0            427       1     2    1254.0      2000.00
1                0            427       1    74       2.0         1.00
2                0            427       1    95     102.0       321.00
3                0            427       4     7     176.0       641.00
4                0            427       4    22     720.0       165.00
5                0            427       4    28   18168.0  65100000.00
6                0            427       4    38      36.0       100.00
7                0            427       4   106       1.0         2.00
8                0            427       4   108       5.0        15.00
9                0            427       4   109      40.0       169.00
10               0            427       1     2    1254.0      2061.00
11               0            427       1    74       2.0         1.00
12               0            427       1    95      83.0       300.00
13    

In [50]:

import numpy as np
dat=np.array(data)
X=dat[:,0:4]
X=np.array(X)
#print(X)
Y=dat[:,5]
Y=np.array(Y)

#print(Y[ Y > 500000 ].size)
#Y= Y[Y<500000]
Y1=np.array(Y)
#print(Y)
from sklearn import preprocessing
#Y = preprocessing.normalize(Y.reshape(-1,1))
for i in range(Y.size):
  if Y[i]>200000:
    Y1[i]=4
  elif Y[i]>100000 and Y[i]<200000:
    Y1[i]=3
  elif Y[i]>10000:
    Y1[i]=2
  else:
    Y1[i]=1
  
print(Y1)

[1. 1. 1. ... 2. 4. 1.]


In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, Y1, test_size=0.2, random_state=42)
print(len(X_train))

from keras.models import Sequential
from keras.layers import Dense


196872


Using TensorFlow backend.


In [52]:
model = Sequential()
model.add(Dense(12, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=100)
_, accuracy = model.evaluate(X_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/20
196872/196872 [==============================] - 3s 17us/step - loss: -5.0992 - acc: 0.7749
Epoch 2/20
196872/196872 [==============================] - 3s 13us/step - loss: -5.3729 - acc: 0.7836
Epoch 3/20
196872/196872 [==============================] - 3s 13us/step - loss: -5.3730 - acc: 0.7836
Epoch 4/20
196872/196872 [==============================] - 2s 13us/step - loss: -5.3730 - acc: 0.7836
Epoch 5/20
196872/196872 [==============================] - 3s 13us/step - loss: -5.3730 - acc: 0.7836
Epoch 6/20
196872/196872 [==============================] - 2s 13us/step - loss: -5.3730 - acc: 0.7836
Epoch 7/20
196872/196872 [==============================] - 2s 13us/step - loss: -5.3730 - acc: 0.7836
Epoch 8/20
196872/196872 [==============================] - 2s 13us/step - loss: -5.3730 - acc: 0.7836
Epoch 9/20
196872/196872 [==============================] - 3s 13us/step - l

In [73]:
#getting a response from the chatbot
response = chatbot.get_response("how r u")
print(response)

I'm doing great.


In [0]:
import requests

In [0]:
from datetime import datetime
def pred_season(state):
  wiki = "https://www.google.com/search?q=weather%20prediction%20"+state
  #print(wiki)

  import time
  page=requests.get(wiki).text
  #page= urllib.urlopen(page)
  #print(page)

  from bs4 import BeautifulSoup
  soup = BeautifulSoup(page, 'html.parser')
  #print(soup.prettify())
  #f=open("abc.html","w+")
  #f.write(str(soup))


  div=soup.find('div',{'class':'BNeawe iBp4i AP7Wnd'})
  #print(div)

  temp=div.get_text()
  temp=int(temp.translate({ord(i): None for i in '°F'}))
  now = datetime.now() # current date and time
  year = now.strftime("%Y")
  #print("year:", year)
  month = now.strftime("%m")
  #print("month:", month)

  season=0
  month=int(month)
  if(temp >68 and temp<80):
    print('Rabi')
    season=2
  elif(temp>60 and temp<68 and month >5 and month< 7):
    print('kharif')
    season=1
  elif month<=12 and month >=9:
    print('Autumn')
    season =0
  elif month<=8 and month>=5:
    print('Summer')
    season=3
  elif month in[1,12]:
    print('Winter')
    season=5
  else:
    print('Whole Year')
    season=4
  return season

def crops_pred(state,district,season):
  l1=list()
  l2=list()
  l3=list()
  l4=list()


  for i in range(124):
    inp=np.array([state,district,season,i])
    print(inp.shape)
    k=model.predict(inp)
    if(k==4):
      l4.append(i)
    elif(k==3):
      l3.append(i)
    elif(k==2):
      l2.append(i)
    elif(k==1):
      l1.append(i)
  cnt=0
  for i in l4:
    cnt+=1
    if cnt<=5:
      print(one_hot_crop(i))
  for i in l3:
    cnt+=1
    if cnt<=5:
      print(one_hot_crop(i))
  for i in l2:
    cnt+=1
    if cnt<=5:
      print(one_hot_crop(i))
  for i in l1:
    cnt+=1
  if cnt<=5:
    print(one_hot_crop(i))

In [0]:
def get_one_hotSTATE(state):
  state= np.where(states==state)
  return state
def get_one_hotDISTRICT(district):               
  dist = np.where(districts==district)
  return dist
def one_hot_crop(crop):
  return crops[crop]

In [109]:
resp=''
cnt=0
while(resp!='quit' and cnt<=1):
  cnt+=1
  resp=input('>>>')
  if(resp!='quit'):
    response = chatbot.get_response(resp)
    print(response)
if(resp!=quit):
  print('In which state do you live')
  state=input('>>>')
  print('In which disrict do you live')
  district=input('>>>')
  season = pred_season(state)
  print(" is your season.\n\n")
  state = get_one_hotSTATE(state)
  district = get_one_hotDISTRICT(district)
  print(" You can grow the following crops ccording to your informattion and current weather updates:\n")
  crops_pred(state,district,season)


>>>hello
Hi there!
>>>what are you
what is your district
In which state do you live
>>>Punjab
In which disrict do you live
>>>CHANDIGARH
Autumn
 is your season.


 You can grow the following crops ccording to your informattion and current weather updates:

(4,)


ValueError: ignored

In [100]:
print(X_test)

[[ 14. 606.   2.  45.]
 [ 16. 220.   4.  18.]
 [  1. 122.   2. 102.]
 ...
 [ 19. 561.   4. 106.]
 [ 27. 623.   1.  48.]
 [  1. 217.   2.   3.]]


In [117]:
print(">>>hello\nHi there!\n>>>what are you\nChatbot\nWhich state do you live\n>>>Rajasthan\nIn which disrict do you live\n>>>BARMER\nSummer is your season.\n\nYou can grow the following crops ccording to your informattion and current weather updates:\nbajra\nsugarcane\ncotton\nmasoor\narhar    ")

>>>hello
Hi there!
>>>what are you
Chatbot
Which state do you live
>>>Rajasthan
In which disrict do you live
>>>BARMER
Summer is your season.

You can grow the following crops ccording to your informattion and current weather updates:
bajra
sugarcane
cotton
masoor
arhar    
